@node ax_add_recursive_am_macro_static
@unnumberedsec ax_add_recursive_am_macro_static

@majorheading Synopsis

@smallexample
AX_ADD_RECURSIVE_AM_MACRO_STATIC([TARGET],[RULE])
@end smallexample

@majorheading Description

Adds the specified rule to AMINCLUDE_STATIC along with a
TARGET-recursive rule that will call TARGET for the current directory
and TARGET-am recursively for each subdirectory.

@majorheading Source Code

Download the
@uref{http://git.savannah.gnu.org/gitweb/?p=autoconf-archive.git;a=blob_plain;f=m4/ax_add_recursive_am_macro_static.m4,latest
version of @file{ax_add_recursive_am_macro_static.m4}} or browse
@uref{http://git.savannah.gnu.org/gitweb/?p=autoconf-archive.git;a=history;f=m4/ax_add_recursive_am_macro_static.m4,the
macro's revision history}.

@majorheading License

@w{Copyright @copyright{} 2009 Tom Howard @email{tomhoward@@users.sf.net}} @* @w{Copyright @copyright{} 2009 Allan Caffee @email{allan.caffee@@gmail.com}}

Copying and distribution of this file, with or without modification, are
permitted in any medium without royalty provided the copyright notice
and this notice are preserved. This file is offered as-is, without any
warranty.
