@node ax_boost_test_exec_monitor
@unnumberedsec ax_boost_test_exec_monitor

@majorheading Synopsis

@smallexample
AX_BOOST_TEST_EXEC_MONITOR
@end smallexample

@majorheading Description

Test for Test_Exec_Monitor library from the Boost C++ libraries. The
macro requires a preceding call to AX_BOOST_BASE. Further documentation
is available at <http://randspringer.de/boost/index.html>.

This macro calls:

@smallexample
  AC_SUBST(BOOST_TEST_EXEC_MONITOR_LIB)
@end smallexample

And sets:

@smallexample
  HAVE_BOOST_TEST_EXEC_MONITOR
@end smallexample

@majorheading Source Code

Download the
@uref{http://git.savannah.gnu.org/gitweb/?p=autoconf-archive.git;a=blob_plain;f=m4/ax_boost_test_exec_monitor.m4,latest
version of @file{ax_boost_test_exec_monitor.m4}} or browse
@uref{http://git.savannah.gnu.org/gitweb/?p=autoconf-archive.git;a=history;f=m4/ax_boost_test_exec_monitor.m4,the
macro's revision history}.

@majorheading License

@w{Copyright @copyright{} 2008 Dodji Seketeli @email{dodji@@seketeli.org}} @* @w{Copyright @copyright{} 2008 Thomas Porschberg @email{thomas@@randspringer.de}}

Copying and distribution of this file, with or without modification, are
permitted in any medium without royalty provided the copyright notice
and this notice are preserved. This file is offered as-is, without any
warranty.
