@node ax_cpu_vendor
@unnumberedsec ax_cpu_vendor

@majorheading Synopsis

@smallexample
AX_CPU_VENDOR
@end smallexample

@majorheading Description

Find your CPU's vendor by requesting cpuid and define "ax_cv_cpu_vendor"
accordingly. This macro depends on AX_GCC_X86_CPUID.

@majorheading Source Code

Download the
@uref{http://git.savannah.gnu.org/gitweb/?p=autoconf-archive.git;a=blob_plain;f=m4/ax_cpu_vendor.m4,latest
version of @file{ax_cpu_vendor.m4}} or browse
@uref{http://git.savannah.gnu.org/gitweb/?p=autoconf-archive.git;a=history;f=m4/ax_cpu_vendor.m4,the
macro's revision history}.

@majorheading License

@w{Copyright @copyright{} 2008 Christophe Tournayre @email{turn3r@@users.sourceforge.net}}

Copying and distribution of this file, with or without modification, are
permitted in any medium without royalty provided the copyright notice
and this notice are preserved. This file is offered as-is, without any
warranty.
