@node ax_c_restrict
@unnumberedsec ax_c_restrict

@majorheading Synopsis

@smallexample
AX_C_RESTRICT
@end smallexample

@majorheading Description

This macro checks if the C99 restrict keyword is broken with the current
compiler and optimizations settings. If broken, it undefines restrict to
do no harm. As of 2019 gcc since 5.0 and clang since 6.0 (June 2017) are
known to be broken and not yet fixed. See
https://github.com/rust-lang/rust/issues/54878 with the links to the gcc
and clang tickets.

@majorheading Source Code

Download the
@uref{http://git.savannah.gnu.org/gitweb/?p=autoconf-archive.git;a=blob_plain;f=m4/ax_c_restrict.m4,latest
version of @file{ax_c_restrict.m4}} or browse
@uref{http://git.savannah.gnu.org/gitweb/?p=autoconf-archive.git;a=history;f=m4/ax_c_restrict.m4,the
macro's revision history}.

@majorheading License

@w{Copyright @copyright{} 2019 Reini Urban @email{rurban@@cpan.org}}

Copying and distribution of this file, with or without modification, are
permitted in any medium without royalty provided the copyright notice
and this notice are preserved. This file is offered as-is, without any
warranty.
