@node ax_check_strftime
@unnumberedsec ax_check_strftime

@majorheading Synopsis

@smallexample
AX_CHECK_STRFTIME
@end smallexample

@majorheading Description

Check for existence and functioning of strftime routine.

@majorheading Source Code

Download the
@uref{http://git.savannah.gnu.org/gitweb/?p=autoconf-archive.git;a=blob_plain;f=m4/ax_check_strftime.m4,latest
version of @file{ax_check_strftime.m4}} or browse
@uref{http://git.savannah.gnu.org/gitweb/?p=autoconf-archive.git;a=history;f=m4/ax_check_strftime.m4,the
macro's revision history}.

@majorheading License

@w{Copyright @copyright{} 2008 Bruce Korb @email{bkorb@@gnu.org}}

Copying and distribution of this file, with or without modification, are
permitted in any medium without royalty provided the copyright notice
and this notice are preserved. This file is offered as-is, without any
warranty.
