@node ax_check_symbol
@unnumberedsec ax_check_symbol

@majorheading Synopsis

@smallexample
AX_CHECK_SYMBOL(SYMBOL, HEADER... [,ACTION-IF-FOUND [,ACTION-IF-NOT-FOUND]])
@end smallexample

@majorheading Description

A wrapper around AC_EGREP_HEADER. The shellvar $ac_found will hold the
HEADER-name that had been containing the symbol. This value is shown to
the user.

@majorheading Source Code

Download the
@uref{http://git.savannah.gnu.org/gitweb/?p=autoconf-archive.git;a=blob_plain;f=m4/ax_check_symbol.m4,latest
version of @file{ax_check_symbol.m4}} or browse
@uref{http://git.savannah.gnu.org/gitweb/?p=autoconf-archive.git;a=history;f=m4/ax_check_symbol.m4,the
macro's revision history}.

@majorheading License

@w{Copyright @copyright{} 2008 Guido U. Draheim @email{guidod@@gmx.de}}

Copying and distribution of this file, with or without modification, are
permitted in any medium without royalty provided the copyright notice
and this notice are preserved.  This file is offered as-is, without any
warranty.
