@node ax_cxx_template_qualified_base_class
@unnumberedsec ax_cxx_template_qualified_base_class

@majorheading Synopsis

@smallexample
AX_CXX_TEMPLATE_QUALIFIED_BASE_CLASS
@end smallexample

@majorheading Description

If the compiler supports template-qualified base class specifiers,
define HAVE_TEMPLATE_QUALIFIED_BASE_CLASS.

@majorheading Source Code

Download the
@uref{http://git.savannah.gnu.org/gitweb/?p=autoconf-archive.git;a=blob_plain;f=m4/ax_cxx_template_qualified_base_class.m4,latest
version of @file{ax_cxx_template_qualified_base_class.m4}} or browse
@uref{http://git.savannah.gnu.org/gitweb/?p=autoconf-archive.git;a=history;f=m4/ax_cxx_template_qualified_base_class.m4,the
macro's revision history}.

@majorheading License

@w{Copyright @copyright{} 2008 Todd Veldhuizen} @* @w{Copyright @copyright{} 2008 Luc Maisonobe @email{luc@@spaceroots.org}}

Copying and distribution of this file, with or without modification, are
permitted in any medium without royalty provided the copyright notice
and this notice are preserved. This file is offered as-is, without any
warranty.
