@node ax_check_docbook_dtd
@unnumberedsec ax_check_docbook_dtd

@majorheading Synopsis

@smallexample
AX_CHECK_DOCBOOK_DTD([dtd-version])
@end smallexample

@majorheading Description

Check for access to a docbook DTD of a particular revision. This macro
can be used for multiple versions within the same script.

Input:

$1 is the version of docbook to search for; default 'current'.

Output:

$HAVE_DOCBOOK_DTD_VERS will be set to 'yes' or 'no' depending on the
results of the test, where VERS is $1, with '_' substituted for '.'
$HAVE_DOCBOOK_DTD will also be set to the same value.

Example:

@smallexample
 AX_CHECK_DOCBOOK_DTD(4.3)
 if test "x$HAVE_DOCBOOK_DTD_4_3" = "xyes"; then
 ...
@end smallexample

@majorheading Source Code

Download the
@uref{http://git.savannah.gnu.org/gitweb/?p=autoconf-archive.git;a=blob_plain;f=m4/ax_check_docbook_dtd.m4,latest
version of @file{ax_check_docbook_dtd.m4}} or browse
@uref{http://git.savannah.gnu.org/gitweb/?p=autoconf-archive.git;a=history;f=m4/ax_check_docbook_dtd.m4,the
macro's revision history}.

@majorheading License

@w{Copyright @copyright{} 2008 Zmanda Inc. @email{http://www.zmanda.com/}} @* @w{Copyright @copyright{} 2008 Dustin J. Mitchell @email{dustin@@zmanda.com}}

This program is free software; you can redistribute it and/or modify it
under the terms of the GNU General Public License as published by the
Free Software Foundation; either version 2 of the License, or (at your
option) any later version.

This program is distributed in the hope that it will be useful, but
WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU General
Public License for more details.

You should have received a copy of the GNU General Public License along
with this program. If not, see <https://www.gnu.org/licenses/>.

As a special exception, the respective Autoconf Macro's copyright owner
gives unlimited permission to copy, distribute and modify the configure
scripts that are the output of Autoconf when processing the Macro. You
need not follow the terms of the GNU General Public License when using
or distributing such scripts, even though portions of the text of the
Macro appear in them. The GNU General Public License (GPL) does govern
all other use of the material that constitutes the Autoconf Macro.

This special exception to the GPL applies to versions of the Autoconf
Macro released by the Autoconf Archive. When you make and distribute a
modified version of the Autoconf Macro, you may extend this special
exception to the GPL to apply to your modified version as well.
