@node ax_cxx_extern_template
@unnumberedsec ax_cxx_extern_template

@majorheading Synopsis

@smallexample
AX_CXX_EXTERN_TEMPLATE
@end smallexample

@majorheading Description

Test whether the C++ compiler supports "extern template".

@majorheading Source Code

Download the
@uref{http://git.savannah.gnu.org/gitweb/?p=autoconf-archive.git;a=blob_plain;f=m4/ax_cxx_extern_template.m4,latest
version of @file{ax_cxx_extern_template.m4}} or browse
@uref{http://git.savannah.gnu.org/gitweb/?p=autoconf-archive.git;a=history;f=m4/ax_cxx_extern_template.m4,the
macro's revision history}.

@majorheading License

@w{Copyright @copyright{} 2008 Patrick Mauritz @email{oxygene@@studentenbude.ath.cx}}

Copying and distribution of this file, with or without modification, are
permitted in any medium without royalty provided the copyright notice
and this notice are preserved. This file is offered as-is, without any
warranty.
