@node ax_cxx_compile_stdcxx_11
@unnumberedsec ax_cxx_compile_stdcxx_11

@majorheading Synopsis

@smallexample
AX_CXX_COMPILE_STDCXX_11([ext|noext], [mandatory|optional])
@end smallexample

@majorheading Description

Check for baseline language coverage in the compiler for the C++11
standard; if necessary, add switches to CXX and CXXCPP to enable
support.

This macro is a convenience alias for calling the AX_CXX_COMPILE_STDCXX
macro with the version set to C++11.  The two optional arguments are
forwarded literally as the second and third argument respectively.
Please see the documentation for the AX_CXX_COMPILE_STDCXX macro for
more information.  If you want to use this macro, you also need to
download the ax_cxx_compile_stdcxx.m4 file.

@majorheading Source Code

Download the
@uref{http://git.savannah.gnu.org/gitweb/?p=autoconf-archive.git;a=blob_plain;f=m4/ax_cxx_compile_stdcxx_11.m4,latest
version of @file{ax_cxx_compile_stdcxx_11.m4}} or browse
@uref{http://git.savannah.gnu.org/gitweb/?p=autoconf-archive.git;a=history;f=m4/ax_cxx_compile_stdcxx_11.m4,the
macro's revision history}.

@majorheading License

@w{Copyright @copyright{} 2008 Benjamin Kosnik @email{bkoz@@redhat.com}} @* @w{Copyright @copyright{} 2012 Zack Weinberg @email{zackw@@panix.com}} @* @w{Copyright @copyright{} 2013 Roy Stogner @email{roystgnr@@ices.utexas.edu}} @* @w{Copyright @copyright{} 2014, 2015 Google Inc.; contributed by Alexey Sokolov @email{sokolov@@google.com}} @* @w{Copyright @copyright{} 2015 Paul Norman @email{penorman@@mac.com}} @* @w{Copyright @copyright{} 2015 Moritz Klammler @email{moritz@@klammler.eu}}

Copying and distribution of this file, with or without modification, are
permitted in any medium without royalty provided the copyright notice
and this notice are preserved. This file is offered as-is, without any
warranty.
