@node ax_ext_have_lib
@unnumberedsec ax_ext_have_lib

@majorheading Synopsis

@smallexample
AX_EXT_HAVE_LIB(<directories>, <library>, <function>, <extra libraries>)
@end smallexample

@majorheading Description

AX_EXT_HAVE_LIB is identical to AC_SEARCH_LIBS with the exception that
will add -L<directory> when looking, and use a different variable for
each directory.

Any required -L<directory> flags are added to LDFLAGS and located
libraies are added to LIBS

Some libraries are unlinkable without other extra libraries, which can
be specified in the 4th argument. The mysql client library needs -lz,
for example.

Example:

@smallexample
 AX_EXT_HAVE_LIB(/lib /usr/lib /usr/local/lib /usr/lib/mysql /usr/local/mysql/lib, mysqlclient, mysql_init, [-lz])
@end smallexample

which finds the mysql client library if succeeds system when it tries
with -L/usr/lib/mysql then it adds -lmysqlclient to LIBS and
-L/usr/lib/mysql to LDFLAGS.

The test itself is based on the autoconf 2.53 version of AC_SEARCH_LIBS.

@majorheading Source Code

Download the
@uref{http://git.savannah.gnu.org/gitweb/?p=autoconf-archive.git;a=blob_plain;f=m4/ax_ext_have_lib.m4,latest
version of @file{ax_ext_have_lib.m4}} or browse
@uref{http://git.savannah.gnu.org/gitweb/?p=autoconf-archive.git;a=history;f=m4/ax_ext_have_lib.m4,the
macro's revision history}.

@majorheading License

@w{Copyright @copyright{} 2008 Duncan Simpson @email{dps@@simpson.demon.co.uk}}

Copying and distribution of this file, with or without modification, are
permitted in any medium without royalty provided the copyright notice
and this notice are preserved. This file is offered as-is, without any
warranty.
