@node ax_fc_check_define
@unnumberedsec ax_fc_check_define

@majorheading Synopsis

@smallexample
AX_FC_CHECK_DEFINE([symbol], [ACTION-IF-FOUND], [ACTION-IF-NOT])
@end smallexample

@majorheading Description

This macro checks to see if the Fortran pre-processor has a symbol
defined.

Consider a usage like:

@smallexample
  AC_FC_PP_DEFINE()
  AX_FC_CHECK_DEFINE(__BIGGEST_ALIGNMENT__, [],
                     AX_APPEND_FLAG([$@{FC_DEFINE@}__BIGGEST_ALIGNMENT__=64],
                                    [FCFLAGS]))
@end smallexample

@majorheading Source Code

Download the
@uref{http://git.savannah.gnu.org/gitweb/?p=autoconf-archive.git;a=blob_plain;f=m4/ax_fc_check_define.m4,latest
version of @file{ax_fc_check_define.m4}} or browse
@uref{http://git.savannah.gnu.org/gitweb/?p=autoconf-archive.git;a=history;f=m4/ax_fc_check_define.m4,the
macro's revision history}.

@majorheading License

@w{Copyright @copyright{} 2016 Timothy Brown @email{tbrown@@freeshell.org}}

Copying and distribution of this file, with or without modification, are
permitted in any medium without royalty provided the copyright notice
and this notice are preserved. This file is offered as-is, without any
warranty.
