@node ax_f90_module
@unnumberedsec ax_f90_module

@majorheading Synopsis

@smallexample
AX_F90_MODULE(MODULE, MODULE-REGEXP, FUNCTION-BODY [, SEARCH-PATH [, ACTION-IF-FOUND [, ACTION-IF-NOT-FOUND]]])
@end smallexample

@majorheading Description

Set up the compiler flags to use a given fortran 90 module MODULE is the
name of the module. MODULE-REGEXP is a regular expression (used by find)
matched by the filename of the module. FUNCTION-BODY is the body of a
function (including the 'use' statement and the call to a function
defined by the module) SEARCH-PATH is a colon-separated list of
directories that will be recursively searched for modules files. If
empty, the search path will be composed of $prefix, $ac_default_prefix,
and all directories exactly one level *above* the directories in
$LD_LIBRARY_PATH (the rationale is that when libraries are put in
/some/path/lib, the modules are often put in a directory like
/some/path/include or /some/path/mod or something similar). An output
variable named F90_MODULE_xxx will be set up with the proper flag for
substitution in Makefiles (xxx is built from the first argument, with
autoconf traditional escapes).

@majorheading Source Code

Download the
@uref{http://git.savannah.gnu.org/gitweb/?p=autoconf-archive.git;a=blob_plain;f=m4/ax_f90_module.m4,latest
version of @file{ax_f90_module.m4}} or browse
@uref{http://git.savannah.gnu.org/gitweb/?p=autoconf-archive.git;a=history;f=m4/ax_f90_module.m4,the
macro's revision history}.

@majorheading License

@w{Copyright @copyright{} 2009 Luc Maisonobe @email{luc@@spaceroots.org}}

Copying and distribution of this file, with or without modification, are
permitted in any medium without royalty provided the copyright notice
and this notice are preserved. This file is offered as-is, without any
warranty.
