@node ax_forceinline
@unnumberedsec ax_forceinline

@majorheading Synopsis

@smallexample
AX_FORCEINLINE()
@end smallexample

@majorheading Description

Provides a test for C compiler support of forced inlining.  If usable,
#define FORCEINLINE to the appropriate force inline keyword.  Otherwise
#define FORCEINLINE to be 'inline'.

@majorheading Source Code

Download the
@uref{http://git.savannah.gnu.org/gitweb/?p=autoconf-archive.git;a=blob_plain;f=m4/ax_forceinline.m4,latest
version of @file{ax_forceinline.m4}} or browse
@uref{http://git.savannah.gnu.org/gitweb/?p=autoconf-archive.git;a=history;f=m4/ax_forceinline.m4,the
macro's revision history}.

@majorheading License

@w{Copyright @copyright{} 2008 Alan Woodland @email{ajw05@@aber.ac.uk}} @* @w{Copyright @copyright{} 2009 Rhys Ulerich @email{rhys.ulerich@@gmail.com}}

Copying and distribution of this file, with or without modification, are
permitted in any medium without royalty provided the copyright notice
and this notice are preserved. This file is offered as-is, without any
warranty.
