@node ax_int128
@unnumberedsec ax_int128

@majorheading Synopsis

@smallexample
AX_HAVE_INT128
@end smallexample

@majorheading Description

Check whether the compiler provides __int128. If so, define HAVE_INT128.

Works with GCC >= 4.6.

TODO: Provide int128[u]_t & work with other compilers.

@majorheading Source Code

Download the
@uref{http://git.savannah.gnu.org/gitweb/?p=autoconf-archive.git;a=blob_plain;f=m4/ax_int128.m4,latest
version of @file{ax_int128.m4}} or browse
@uref{http://git.savannah.gnu.org/gitweb/?p=autoconf-archive.git;a=history;f=m4/ax_int128.m4,the
macro's revision history}.

@majorheading License

@w{Copyright @copyright{} 2019 Reuben Thomas @email{rrt@@sc3d.org}}

Copying and distribution of this file, with or without modification, are
permitted in any medium without royalty provided the copyright notice
and this notice are preserved. This file is offered as-is, without any
warranty.
