@node ax_java_check_class
@unnumberedsec ax_java_check_class

@majorheading Synopsis

@smallexample
AX_JAVA_CHECK_CLASS(<class>,<action-if-found>,<action-if-not-found>)
@end smallexample

@majorheading Description

Test if a Java class is available. Based on AX_PROG_JAVAC_WORKS. This
version uses a cache variable which is both compiler, options and
classpath dependent (so if you switch from javac to gcj it correctly
notices and redoes the test).

The macro tries to compile a minimal program importing <class>. Some
newer compilers moan about the failure to use this but fail or produce a
class file anyway. All moaning is sunk to /dev/null since I only wanted
to know if the class could be imported. This is a recommended followup
to AX_CHECK_JAVA_PLUGIN with classpath appropriately adjusted.

@majorheading Source Code

Download the
@uref{http://git.savannah.gnu.org/gitweb/?p=autoconf-archive.git;a=blob_plain;f=m4/ax_java_check_class.m4,latest
version of @file{ax_java_check_class.m4}} or browse
@uref{http://git.savannah.gnu.org/gitweb/?p=autoconf-archive.git;a=history;f=m4/ax_java_check_class.m4,the
macro's revision history}.

@majorheading License

@w{Copyright @copyright{} 2008 Duncan Simpson @email{dps@@simpson.demon.co.uk}}

This program is free software; you can redistribute it and/or modify it
under the terms of the GNU General Public License as published by the
Free Software Foundation; either version 2 of the License, or (at your
option) any later version.

This program is distributed in the hope that it will be useful, but
WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU General
Public License for more details.

You should have received a copy of the GNU General Public License along
with this program. If not, see <https://www.gnu.org/licenses/>.

As a special exception, the respective Autoconf Macro's copyright owner
gives unlimited permission to copy, distribute and modify the configure
scripts that are the output of Autoconf when processing the Macro. You
need not follow the terms of the GNU General Public License when using
or distributing such scripts, even though portions of the text of the
Macro appear in them. The GNU General Public License (GPL) does govern
all other use of the material that constitutes the Autoconf Macro.

This special exception to the GPL applies to versions of the Autoconf
Macro released by the Autoconf Archive. When you make and distribute a
modified version of the Autoconf Macro, you may extend this special
exception to the GPL to apply to your modified version as well.
