@node ax_lib_id3
@unnumberedsec ax_lib_id3

@majorheading Synopsis

@smallexample
AX_LIB_ID3([ACTION-IF-TRUE], [ACTION-IF-FALSE])
@end smallexample

@majorheading Description

This macro will check for the existence of id3lib
(http://id3lib.sourceforge.net/). It does this by checking for the
header file id3.h and the id3 library object file. A --with-id3lib
option is supported as well. The following output variables are set with
AC_SUBST:

@smallexample
  ID3_CPPFLAGS
  ID3_LDFLAGS
  ID3_LIBS
@end smallexample

You can use them like this in Makefile.am:

@smallexample
  AM_CPPFLAGS = $(ID3_CPPFLAGS)
  AM_LDFLAGS = $(ID3_LDFLAGS)
  program_LDADD = $(ID3_LIBS)
@end smallexample

Additionally, the C preprocessor symbol HAVE_ID3LIB will be defined with
AC_DEFINE if id3lib is available.

@majorheading Source Code

Download the
@uref{http://git.savannah.gnu.org/gitweb/?p=autoconf-archive.git;a=blob_plain;f=m4/ax_lib_id3.m4,latest
version of @file{ax_lib_id3.m4}} or browse
@uref{http://git.savannah.gnu.org/gitweb/?p=autoconf-archive.git;a=history;f=m4/ax_lib_id3.m4,the
macro's revision history}.

@majorheading License

@w{Copyright @copyright{} 2009 Oskar Liljeblad @email{oskar@@osk.mine.nu}}

Copying and distribution of this file, with or without modification, are
permitted in any medium without royalty provided the copyright notice
and this notice are preserved. This file is offered as-is, without any
warranty.
