@node ax_lib_xml_security
@unnumberedsec ax_lib_xml_security

@majorheading Synopsis

@smallexample
AX_LIB_XML_SECURITY([MINIMUM-VERSION])
@end smallexample

@majorheading Description

This macro provides tests of availability of Apache Xml-Security C++
library <http://santuario.apache.org/index.html> of particular version
or newer. This macros checks for Apache Xml-Security C++ headers and
libraries and defines compilation flags

Macro supports following options and their values:

1) Single-option usage:

@smallexample
  --with-xml-security - yes, no or path to Xml-Security installation prefix
@end smallexample

2) Three-options usage (all options are required):

@smallexample
  --with-xml-security=yes
  --with-xml-security-inc - path to base directory with Xml-Security headers
  --with-xml-security-lib - linker flags for Xml-Security
@end smallexample

This macro calls:

@smallexample
  AC_SUBST(XML_SECURITY_CFLAGS)
  AC_SUBST(XML_SECURITY_LDFLAGS)
  AC_SUBST(XML_SECURITY_VERSION) - only if version requirement is used
@end smallexample

And sets:

@smallexample
  HAVE_XML_SECURITY
@end smallexample

@majorheading Source Code

Download the
@uref{http://git.savannah.gnu.org/gitweb/?p=autoconf-archive.git;a=blob_plain;f=m4/ax_lib_xml_security.m4,latest
version of @file{ax_lib_xml_security.m4}} or browse
@uref{http://git.savannah.gnu.org/gitweb/?p=autoconf-archive.git;a=history;f=m4/ax_lib_xml_security.m4,the
macro's revision history}.

@majorheading License

@w{Copyright @copyright{} 2008 Alexander Petry @email{petry@@itwm.fhg.de}} @* @w{Copyright @copyright{} 2008 Mateusz Loskot @email{mateusz@@loskot.net}}

Copying and distribution of this file, with or without modification, are
permitted in any medium without royalty provided the copyright notice
and this notice are preserved. This file is offered as-is, without any
warranty.
