@node ax_lib_sqlite3
@unnumberedsec ax_lib_sqlite3

@majorheading Synopsis

@smallexample
AX_LIB_SQLITE3([MINIMUM-VERSION])
@end smallexample

@majorheading Description

Test for the SQLite 3 library of a particular version (or newer)

This macro takes only one optional argument, required version of SQLite
3 library. If required version is not passed, 3.0.0 is used in the test
of existence of SQLite 3.

If no installation prefix to the installed SQLite library is given the
macro searches under /usr, /usr/local, and /opt.

This macro calls:

@smallexample
  AC_SUBST(SQLITE3_CFLAGS)
  AC_SUBST(SQLITE3_LDFLAGS)
  AC_SUBST(SQLITE3_VERSION)
@end smallexample

And sets:

@smallexample
  HAVE_SQLITE3
@end smallexample

@majorheading Source Code

Download the
@uref{http://git.savannah.gnu.org/gitweb/?p=autoconf-archive.git;a=blob_plain;f=m4/ax_lib_sqlite3.m4,latest
version of @file{ax_lib_sqlite3.m4}} or browse
@uref{http://git.savannah.gnu.org/gitweb/?p=autoconf-archive.git;a=history;f=m4/ax_lib_sqlite3.m4,the
macro's revision history}.

@majorheading License

@w{Copyright @copyright{} 2008 Mateusz Loskot @email{mateusz@@loskot.net}}

Copying and distribution of this file, with or without modification, are
permitted in any medium without royalty provided the copyright notice
and this notice are preserved. This file is offered as-is, without any
warranty.
