@node ax_lib_mysql
@unnumberedsec ax_lib_mysql

@majorheading Synopsis

@smallexample
AX_LIB_MYSQL([MINIMUM-VERSION])
@end smallexample

@majorheading Description

This macro provides tests of availability of MySQL client library of
particular version or newer.

AX_LIB_MYSQL macro takes only one argument which is optional. If there
is no required version passed, then macro does not run version test.

The --with-mysql option takes one of three possible values:

no - do not check for MySQL client library

yes - do check for MySQL library in standard locations (mysql_config
should be in the PATH)

path - complete path to mysql_config utility, use this option if
mysql_config can't be found in the PATH

This macro calls:

@smallexample
  AC_SUBST(MYSQL_CFLAGS)
  AC_SUBST(MYSQL_LDFLAGS)
  AC_SUBST(MYSQL_VERSION)
@end smallexample

And sets:

@smallexample
  HAVE_MYSQL
@end smallexample

@majorheading Source Code

Download the
@uref{http://git.savannah.gnu.org/gitweb/?p=autoconf-archive.git;a=blob_plain;f=m4/ax_lib_mysql.m4,latest
version of @file{ax_lib_mysql.m4}} or browse
@uref{http://git.savannah.gnu.org/gitweb/?p=autoconf-archive.git;a=history;f=m4/ax_lib_mysql.m4,the
macro's revision history}.

@majorheading License

@w{Copyright @copyright{} 2008 Mateusz Loskot @email{mateusz@@loskot.net}}

Copying and distribution of this file, with or without modification, are
permitted in any medium without royalty provided the copyright notice
and this notice are preserved. This file is offered as-is, without any
warranty.
