@node ax_ruby_devel
@unnumberedsec ax_ruby_devel

@majorheading Synopsis

@smallexample
AX_RUBY_DEVEL([version])
@end smallexample

@majorheading Description

This macro checks for Ruby and tries to get the include path to
'ruby.h'. It provides the $(RUBY_CPPFLAGS) and $(RUBY_LDFLAGS) output
variables. It also exports $(RUBY_EXTRA_LIBS) for embedding Ruby in your
code.

You can search for some particular version of Ruby by passing a
parameter to this macro, for example "2.2.1".

@majorheading Source Code

Download the
@uref{http://git.savannah.gnu.org/gitweb/?p=autoconf-archive.git;a=blob_plain;f=m4/ax_ruby_devel.m4,latest
version of @file{ax_ruby_devel.m4}} or browse
@uref{http://git.savannah.gnu.org/gitweb/?p=autoconf-archive.git;a=history;f=m4/ax_ruby_devel.m4,the
macro's revision history}.

@majorheading License

@w{Copyright @copyright{} 2008 Rafal Rzepecki @email{divided.mind@@gmail.com}} @* @w{Copyright @copyright{} 2008 Sebastian Huber @email{sebastian-huber@@web.de}} @* @w{Copyright @copyright{} 2008 Alan W. Irwin} @* @w{Copyright @copyright{} 2008 Rafael Laboissiere @email{rafael@@laboissiere.net}} @* @w{Copyright @copyright{} 2008 Andrew Collier} @* @w{Copyright @copyright{} 2008 Matteo Settenvini @email{matteo@@member.fsf.org}} @* @w{Copyright @copyright{} 2008 Horst Knorr @email{hk_classes@@knoda.org}}

This program is free software: you can redistribute it and/or modify it
under the terms of the GNU General Public License as published by the
Free Software Foundation, either version 3 of the License, or (at your
option) any later version.

This program is distributed in the hope that it will be useful, but
WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU General
Public License for more details.

You should have received a copy of the GNU General Public License along
with this program. If not, see <https://www.gnu.org/licenses/>.

As a special exception, the respective Autoconf Macro's copyright owner
gives unlimited permission to copy, distribute and modify the configure
scripts that are the output of Autoconf when processing the Macro. You
need not follow the terms of the GNU General Public License when using
or distributing such scripts, even though portions of the text of the
Macro appear in them. The GNU General Public License (GPL) does govern
all other use of the material that constitutes the Autoconf Macro.

This special exception to the GPL applies to versions of the Autoconf
Macro released by the Autoconf Archive. When you make and distribute a
modified version of the Autoconf Macro, you may extend this special
exception to the GPL to apply to your modified version as well.
