@node ax_switch_flags
@unnumberedsec ax_switch_flags

@majorheading Synopsis

@smallexample
AX_SWITCH_FLAGS(newnamespace,[oldnamespace])
@end smallexample

@majorheading Description

Switch common compilation flags from temporary variables between two
compilation namespace.

Compilation flags includes: CPPFLAGS, CFLAGS, CXXFLAGS, LDFLAGS, LIBS,
OBJCFLAGS.

By default these flags are restored to a global (empty) namespace, but
user could restore from specific NAMESPACE by using
AX_RESTORE_FLAGS(NAMESPACE) macro.

Typical usage is like:

@smallexample
  AX_SAVE_FLAGS(beginprogram)
  CPPFLAGS="-Imypackagespath $@{CPPFLAGS@}"
  AX_SWITCH_FLAGS(mypackage,beginprogram)
@end smallexample

@majorheading Source Code

Download the
@uref{http://git.savannah.gnu.org/gitweb/?p=autoconf-archive.git;a=blob_plain;f=m4/ax_switch_flags.m4,latest
version of @file{ax_switch_flags.m4}} or browse
@uref{http://git.savannah.gnu.org/gitweb/?p=autoconf-archive.git;a=history;f=m4/ax_switch_flags.m4,the
macro's revision history}.

@majorheading License

@w{Copyright @copyright{} 2009 Filippo Giunchedi @email{filippo@@esaurito.net}} @* @w{Copyright @copyright{} 2011 The Board of Trustees of the Leland Stanford Junior University} @* @w{Copyright @copyright{} 2011 Russ Allbery @email{rra@@stanford.edu}} @* @w{Copyright @copyright{} 2013 Bastien ROUCARIES @email{roucaries.bastien+autoconf@@gmail.com}}

Copying and distribution of this file, with or without modification, are
permitted in any medium without royalty provided the copyright notice
and this notice are preserved. This file is offered as-is, without any
warranty.
