@node ax_with_prog
@unnumberedsec ax_with_prog

@majorheading Synopsis

@smallexample
AX_WITH_PROG([VARIABLE],[program],[VALUE-IF-NOT-FOUND],[PATH])
@end smallexample

@majorheading Description

Locates an installed program binary, placing the result in the precious
variable VARIABLE. Accepts a present VARIABLE, then --with-program, and
failing that searches for program in the given path (which defaults to
the system path). If program is found, VARIABLE is set to the full path
of the binary; if it is not found VARIABLE is set to VALUE-IF-NOT-FOUND
if provided, unchanged otherwise.

A typical example could be the following one:

@smallexample
  AX_WITH_PROG(PERL,perl)
@end smallexample

NOTE: This macro is based upon the original AX_WITH_PYTHON macro from
Dustin J. Mitchell <dustin@@cs.uchicago.edu>.

@majorheading Source Code

Download the
@uref{http://git.savannah.gnu.org/gitweb/?p=autoconf-archive.git;a=blob_plain;f=m4/ax_with_prog.m4,latest
version of @file{ax_with_prog.m4}} or browse
@uref{http://git.savannah.gnu.org/gitweb/?p=autoconf-archive.git;a=history;f=m4/ax_with_prog.m4,the
macro's revision history}.

@majorheading License

@w{Copyright @copyright{} 2008 Francesco Salvestrini @email{salvestrini@@users.sourceforge.net}} @* @w{Copyright @copyright{} 2008 Dustin J. Mitchell @email{dustin@@cs.uchicago.edu}}

Copying and distribution of this file, with or without modification, are
permitted in any medium without royalty provided the copyright notice
and this notice are preserved. This file is offered as-is, without any
warranty.
