@node ax_zoneinfo
@unnumberedsec ax_zoneinfo

@majorheading Synopsis

@smallexample
AX_ZONEINFO([options...])
@end smallexample

@majorheading Description

This macro finds compiled zoneinfo files.  If successful it will define
HAVE_ZONEINFO per:

@smallexample
  AC_DEFINE([HAVE_ZONEINFO], [1], [...])
@end smallexample

and have the variable TZDIR point to the zoneinfo directory as per

@smallexample
  AC_SUBST([TZDIR])
  AC_DEFINE_UNQUOTED([TZDIR], [/path/to/zic/files], [...])
@end smallexample

Optionally, OPTIONS can be `right' to trigger further tests that will
determine if leap second fix-ups are available.  If so the variables
HAVE_ZONEINFO_RIGHT, ZONEINFO_UTC_RIGHT and TZDIR_RIGHT will be
populated:

@smallexample
  AC_DEFINE([HAVE_ZONEINFO_RIGHT], [1], [...])
  AC_SUBST([TZDIR_RIGHT])
  AC_DEFINE_UNQUOTED([TZDIR_RIGHT], [/path/to/right/zic/files], [...])
  AC_SUBST([ZONEINFO_UTC_RIGHT])
  AC_DEFINE_UNQUOTED([ZONEINFO_UTC_RIGHT], [$ZONEINFO_UTC_RIGHT], [...])
@end smallexample

@majorheading Source Code

Download the
@uref{http://git.savannah.gnu.org/gitweb/?p=autoconf-archive.git;a=blob_plain;f=m4/ax_zoneinfo.m4,latest
version of @file{ax_zoneinfo.m4}} or browse
@uref{http://git.savannah.gnu.org/gitweb/?p=autoconf-archive.git;a=history;f=m4/ax_zoneinfo.m4,the
macro's revision history}.

@majorheading License

@w{Copyright @copyright{} 2012 Sebastian Freundt @email{freundt@@fresse.org}}

Copying and distribution of this file, with or without modification, are
permitted in any medium without royalty provided the copyright notice
and this notice are preserved. This file is offered as-is, without any
warranty.
